version: '3.8'

services:
  api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    container_name: fastapi
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    command: [ "sh", "-c", "alembic upgrade head && uvicorn api.main:app --host 0.0.0.0 --port 8000" ]
  celery:
    image: celery
    container_name: celery
    volumes:
      - ./app:/app
    command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"